### ISSUE TITLE
Facebook upload broken

### ISSUE THREAD

**Issue by X01X012013** [X01X012013/AdBlockProtector#145]
Facebook upload, direct paste and select file, are both broken. 

Update: 
EasyList should be fixing it soon, put this in your filter temporarily if you don't want to wait: 
`@@||upload.facebook.com/ajax/mercury/upload.php`

**Comment by uBlock-user** [comment]
Because of a bad filter from Easylist - https://github.com/gorhill/uBlock/issues/2532

**Comment by X01X012013** [comment]
Well, looks like it's a good time to test `$badfilter`

**Comment by uBlock-user** [comment]
Yeah this would be the filter - `||facebook.com/ajax/*logging$badfilter`

**Comment by uBlock-user** [comment]
But why did you open this as a bug ? This has nothing to do with the Script.

**Comment by X01X012013** [comment]
> But why did you open this as a bug ? This has nothing to do with the Script.

Our goal here is to respond to breakages caused by ad blockers. 

> Yeah this would be the filter - `||facebook.com/ajax/*logging$badfilter`

Eh... looks like FB changed their code so `upload.php` has some weird stuff as parameter and got matched.

**Comment by X01X012013** [comment]
This should be a better fix... I think EasyList will fix it soon, put this in your filter temporarily if you don't want to wait. 
`@@||upload.facebook.com/ajax/mercury/upload.php`

**Comment by VirenMohindra** [comment]
Cheers

**Comment by uBlock-user** [comment]
Gorhill already updated the uBlock filters, so only keep one, don't add both.

**Comment by uBlock-user** [comment]
> Our goal here is to respond to breakages caused by ad blockers. 

This is a filter list issue caused by the authors of Easylist, not breakage caused by uBO.

**Comment by X01X012013** [comment]
Yea, looks like Facebook did it on purpose. EasyList responded: https://github.com/easylist/easylist/commit/ccb52c31d1167a9398ee5cb01f8ed57efdb01a4e

**Comment by uBlock-user** [comment]
Yeah websites sabotaging themselves isn't a surprise anymore.

**Comment by jspenguin2017** [comment]
Well, that's exactly our goal: unbreak websites that breaks themselves.

**Comment by uBlock-user** [comment]
But this issue specifically doesn't fall under this category, this was a filter list issue propagated by a bad filter on Easylist's behalf, facebook changes its system everyday and something new is added or removed which isn't a surprise at this juncture, but that has nothing to do with breaking itself as it's not.

**Comment by jspenguin2017** [comment]
Why are you telling me what falls in the scope of my project?

**Comment by uBlock-user** [comment]
Because I thought this project was about neutralizing the anti adblock scripts and as I also contribute around the project by offering potential solutions ?

**Comment by jspenguin2017** [comment]
Yep, that's right, what Facebook did is exactly that, breaking their own site when ad blocker is active is a form of anti adblock.

**Comment by uBlock-user** [comment]
No it doesn't. I have a profile there and entities such as facebook and google don't indulge themselves by doing such pathetic activities, believe me if you want or not if you don't want to. This kind of filter issues happen because Easylist has a terrible habit of adding a broad filter every now and then and when it breaks something  it gets reported. Anyways I only wanted to know the core reason behind opening this on this issue tracker and now I know, I don't have to offer any further reasoning to you, if you still believe it's doing on purpose. It's alright if we agree to disagree.

**Comment by jspenguin2017** [comment]
The upload request ends with `&logging`, a parameter without a value, which got matched by a filter. The parameter is not needed since it will be parsed to `undefined` anyway. Maybe it was always like this and EasyList didn't test their commit. I didn't dig into their Git history, but anyway, our goal here is to fix everything that is broken about ad blocker, this includes offering temporary solutions for EasyList's bad commits.
