### ISSUE TITLE
*.wp.pl

### ISSUE THREAD

**Issue by Eva850** [X01X012013/AdBlockProtector#21]
wp.pl detects adblock and refuses to play video
Link to video:
http://tech.wp.pl/kat,1009785,title,Zanosi-sie-koniec-darmowych-i-otwartych-sieci-Wi-Fi,wid,18507246,wiadomosc.html?ticaid=117c26
Firefox
Greasemonkey
Ublock Origin

![adblock](https://cloud.githubusercontent.com/assets/20646455/18647910/97d06b3a-7eb8-11e6-94c6-e392180abf36.jpg)
![filters](https://cloud.githubusercontent.com/assets/20646455/18647911/97d2973e-7eb8-11e6-82e4-1a3dfb2d448d.png)
![filters1](https://cloud.githubusercontent.com/assets/20646455/18647912/97da2760-7eb8-11e6-9dd9-ffb253985857.jpg)

**Comment by mikhoul** [comment]
@Eva850 You're lucky there is a bug in the "Anti-Adblock":

Use this filter:

```

! 2016-09-20 14:21:42 http://tech.wp.pl/kat,1009785,title,Zanosi-sie-koniec-darmowych-i-otwartych-sieci-Wi-Fi,wid,18507246,wiadomosc.html?ticaid=117c3b
tech.wp.pl## .windowErrCont
```

To start the video DON'T press the play button, use the "HD" button instead since the protection is not applied to the HD video :laughing:   To pause use the Right Click context menu option.
![GitHub Logo](http://i.imgur.com/rDxzkES.png)

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=- 


@X01X012013

Maybe you should start a "more official" anti-adblock list to replace @reek, till we find him :wink: 

It would be more efficient to have something official where all anti-adblock filters are collected instead of being scattered everywhere.

I would gladly contribute to such list in my spare time :smiley_cat: 

We could even ask to @gorhill to include the list in Ublock to help to have more contributors.

Think about it ! :thought_balloon:

**Comment by Eva850** [comment]
It works for me. Thank you very much!

**Comment by Eva850** [comment]
Can you also check this site? It uses the same anti adblock, but does not have HD button. 
https://portal.abczdrowie.pl/neoerlichioza-nowa-choroba-odkleszczowa

**Comment by mikhoul** [comment]
Try those rules and filters:

**RULES:**
```
portal.abczdrowie.pl https://a.wpimg.pl/a/i/stg/cookie-info.js script allow
portal.abczdrowie.pl https://googleads.g.doubleclick.net/pagead/ads xmlhttprequest allow
portal.abczdrowie.pl https://imasdk.googleapis.com/js/sdkloader script allow
portal.abczdrowie.pl https://p515.atemda.com/video.ashx xmlhttprequest allow
portal.abczdrowie.pl https://pagead2.googlesyndication.com/pagead script allow
portal.abczdrowie.pl https://rek.www.wp.pl/vad.xml xmlhttprequest allow
portal.abczdrowie.pl https://www.googletagmanager.com/gtm.js script allow
```

**FILTERS:**
```
! 2016-09-20 23:04:38 abczdrowie.pl
@@||dot.wp.pl/*/*.gif$domain=portal.abczdrowie.pl

! 2016-09-20 21:40:39 https://portal.abczdrowie.pl/neoerlichioza-nowa-choroba-odkleszczowa
portal.abczdrowie.pl## .windowErrCont

! 2016-09-20 23:25:36 https://portal.abczdrowie.pl/neoerlichioza-nowa-choroba-odkleszczowa
portal.abczdrowie.pl##.a-ctn-d--top.a-ctn-d
```
You must let the page load _completely_ before the video start by itself... took almost one minute here since it have many many many request  😈

**Comment by Eva850** [comment]
It works. Thank you.

**Comment by X01X012013** [comment]
Hi, I'm back. Was very very busy these days. I'll look into this right now.

**Comment by X01X012013** [comment]
`*.wp.pl` broke again.

**Comment by mikhoul** [comment]
It work fine here:   http://i.imgur.com/fsx6s25.png

**Comment by X01X012013** [comment]
@mikhoul Which rules are in your custom rules?
