### ISSUE TITLE
finanzen.net

### ISSUE THREAD

**Issue by tobsen987** [X01X012013/AdBlockProtector#22]
http://www.finanzen.net
http://imgur.com/a/D04D1

Safari 10.0 (12602.1.50.0.10)
Tampermonkey
AdGuard
EasyList + AakList

also:

Google Chrome 53.0.2785.143
Tampermonkey
uBlock Origin
EasyList + AakList

Works with Firefox though..

Site says a browser plugin is preventing correct display of the page and you should disable adblock. CSS file will get unloaded / not load when ablock detected.

**Comment by Superkloton** [comment]
Block script "assetcheck.finanzen.net", works for me on Safari 10.

**Comment by tobsen987** [comment]
And how can i do that? Can't get it to work :(

**Comment by Superkloton** [comment]
I use "JS Blocker 5" for Safari to block scripts but there is certainly an AdBlock filter as well. Unfortunately, I don’t know how a filter for this is supposed to look but you could ask in the AdBlock forum, they always know that stuff there:

https://adblockplus.org/forum/viewtopic.php?f=1&t=47287

(That’s a thread for different website just to show how helpful they are - you would have to start a new thread for finanzen.net)

Doesn’t matter which AdBlocker you use, those filters should work in all of them. Hope you get it to work!

Otherwise, try JS Blocker, it’s a neat tool to make load webpages faster by removing all sorts of ad and tracking scripts.

**Comment by X01X012013** [comment]
Sorry for this delayed response, but I am currently not getting any block screen. 
[screenshot](http://i.imgur.com/pHJ8hYt.png)

**Comment by X01X012013** [comment]
Hi, since there is no response for five days, I will close this issue. Please let me know if anything changes.
