### ISSUE TITLE
ver 2.0.0 problems 

### ISSUE THREAD

**Issue by xxcriticxx** [X01X012013/AdBlockProtector#31]
with ver 2.0.0 on i cant use edit post function on github

i also cant click on check box on cloudflare i`m not a robot captcha

can you please double check this

**Comment by X01X012013** [comment]
Hi, please update to 2.0.2 and try again, if it is still not working, please post your setup, including browser, script host, and AdBlocker.

**Comment by xxcriticxx** [comment]
you have to support the fox man

**Comment by mikhoul** [comment]
@xxcriticxx   I'm pretty sure it's a conflict with Firefox again, since it's not supported a workaround is to allow the script to only run on the websites were you need it with the script manager:  http://i.imgur.com/vVo0aER.png

Even better there will be no listener running on the other pages, I do that for most of my UserScripts it save me lot of problems/bug allowing most scripts to run **ONLY** where they are really useful. :smile_cat:

**Comment by xxcriticxx** [comment]
so add github.com and google.com to this?

**Comment by mikhoul** [comment]
so add github.com and google.com to this?

In fact exclude the script from running on all pages **EXCEPT** the one you allow, it will be more easy and useful this way.  👾

So the script will run ONLY on page where it has to run. :octocat:

**Comment by xxcriticxx** [comment]
@mikhoul can you show me example please?

**Comment by X01X012013** [comment]
Update: 
https://github.com/X01X012013/AdBlockProtector/issues/23#issuecomment-258955091

**Comment by X01X012013** [comment]
Please post in #32 for further discussions.
