### ISSUE TITLE
RAM and CPU usage for wp.pl websites

### ISSUE THREAD

**Issue by xxcriticxx** [X01X012013/AdBlockProtector#45]
@X01X012013 can you check ram usage on firefox with tmonkey. i think something is wrong can we do some testing? am hitting 2 gb ram and about 25% cpu with about 10 to 20 wp.pl tabs open. website is sluggish.

**Comment by X01X012013** [comment]
Since videos are cached on RAM and there are multiple videos per page, with 20 tabs open, I wouldn't be surprised that it hit 2GB. One way to fix it is to unload videos that are on the background too long, I may or may not do it, I don't really have time now. But seriously, why do you need to open 20 tabs? 
A side note is that AdBlock Protector now have AAK code appended, so you no longer need both.

**Comment by X01X012013** [comment]
Also, AdBlock Protector will tick once per second on those pages, which may be a problem, I'll see if I can pause the ticking when the page is in the background.

**Comment by X01X012013** [comment]
Hi, this is patched into Script 5.9, can you test if it helped with CPU usage?

**Comment by X01X012013** [comment]
Since there is no update for a while, I assume that the fix worked.
