### ISSUE TITLE
player.pl

### ISSUE THREAD

**Issue by xxcriticxx** [X01X012013/AdBlockProtector#60]
@X01X012013 this use to be in reek script and doesn't work any longer. please check if you can do something about ad block on this website.

**Comment by X01X012013** [comment]
Do you have a specific test link?

**Comment by xxcriticxx** [comment]
@X01X012013 visit webiste you see adblock all over. i am geolocked because i am in usa. i am also paging @szymon1118 for assistance.

test link:

http://player.pl/programy-online/kuba-wojewodzki-talk-show-odcinki,2497/odcinek-306,kuba-wojewodzki-odcinek-specjalny,S00E306,70253.html?atpl#play

**Comment by X01X012013** [comment]
@xxcriticxx Geo Lock...

**Comment by xxcriticxx** [comment]
@X01X012013 i get you something with pl ip

**Comment by X01X012013** [comment]
@xxcriticxx Yea, let me know if you find a free VPN that has Poland.

**Comment by xxcriticxx** [comment]
@X01X012013 you know of any paid options?

**Comment by xxcriticxx** [comment]
this one has 3 day free trial https://www.goldenfrog.com/vyprvpn/poland-vpn

**Comment by xxcriticxx** [comment]
am talking to the our boys in polish filters to set up something at there house that will work for sure

**Comment by X01X012013** [comment]
@xxcriticxx Since the website is already broken, we can't break it more, so I included `player.pl` to TVN solution. Can you check if it works? Added to Script 6.34

**Comment by xxcriticxx** [comment]
i wont be able to check i am geo locked i get @MajkiIT and/or @F4z check

**Comment by xxcriticxx** [comment]
@X01X012013 here is post from adguard forum:

https://forum.adguard.com/index.php?threads/resolved-player-pl.19371/#post-125569

**Comment by X01X012013** [comment]
Well, we would need someone in Poland to see which solution on that forum works...

**Comment by xxcriticxx** [comment]
i put a request on the pl filters repo already. i will be in touch

**Comment by X01X012013** [comment]
An update here, this issue is handled in https://github.com/MajkiIT/polish-ads-filter/issues/2205
At the time of this post, most videos are working.

**Comment by X01X012013** [comment]
Looks like we aren't getting anywhere, I'll wait another week and then I'll close this issue.

**Comment by xxcriticxx** [comment]
well if @szymon1118 find something new about geo lock that be good

**Comment by szymon1118** [comment]
@xxcriticxx I will still check it from time to time to see if anyone has found a solution and try to find a person who has a Smart TV and is in Poland.

**Comment by X01X012013** [comment]
@szymon1118 The smart TV runs Android, doesn't it? Can you use an emulator?

**Comment by szymon1118** [comment]
@X01X012013 I think that smart TV runs linux but every company modify it so it depends on tv.

**Comment by xxcriticxx** [comment]
Samsung runs on tinzen os or something 

https://en.wikipedia.org/wiki/Tizen

**Comment by X01X012013** [comment]
@szymon1118 
Oh well, I should have Googled before posting that XD
What kind of traffic you are looking for? Can't you generate the traffics with a browser and use Wire Sharks or something to sniff that?

**Comment by szymon1118** [comment]
@X01X012013 I already did it (I have posted links) :smile: but i need to know if sniffed API from android is different from smart tv because when it's the same API response we need to know what's wrong with `ticket` argument. I can't sniff the traffic on my PC because videos are encrypted but on android and smart TV not. Trust me there are many informations about `player.pl` on polish sites and were created some bookmarklet, websites and standalone programs to download materials thence but I'm almost sure that every solution comes from here: svn.sd-xbmc.org/log.php?repname=sd-xbmc&path=%2Ftrunk%2Fxbmc-addons%2Fsrc%2Fplugin.video.polishtv.live%2Fhosts%2Ftvn.py and when something doesn't work anymore eg. there is an API error we are waiting for them to fix it.

**Comment by X01X012013** [comment]
@szymon1118 
Can't you use browser's console to monitor network? You can view requests even if they use `https`. 
![image](https://cloud.githubusercontent.com/assets/7283682/23441848/1b08655e-fde2-11e6-8c0a-1fff705fbca7.png)
Can you sniff the `user agent` that is sent to the server so we can pretend to be the Android app even though we are actually a browser?

**Comment by xxcriticxx** [comment]
i dont think android is HD

**Comment by szymon1118** [comment]
@X01X012013 @xxcriticxx 
I keep tracking some forums and found today answer from an expert (http://sd-xbmc.org/pl/comment/5440#comment-5440) and he aswered that videos which show API error are DRM protected so seems that they are protect all of their latest videos :disappointed:.

**Comment by X01X012013** [comment]
@szymon1118 OK, so replacing the player isn't an option, but can we trick the player into thinking that ads are properly loaded?

**Comment by xxcriticxx** [comment]
@X01X012013 i think DRM only plays if you login and pay but i might be wrong

**Comment by xxcriticxx** [comment]
@szymon1118 can you correct me if am wrong

**Comment by szymon1118** [comment]
@X01X012013 We can try to do this but can you add to your script ` a.cookie("tvn_location2", "1");` and lock ` TvnAdBlockBoardUtils` to an empty function and also disable cosmetic filtering in ublock origin then check if you got a player which is trying to load a video?

@xxcriticxx I think that now they are trying to put DRM to every latest video but I'm not sure. You are right that paid videos are DRM protected and we can't download them but It seems that also free materials are sometimes protected.

**Comment by X01X012013** [comment]
@szymon1118 
I tried: 

Rule: `@@||player.pl$generichide`
Script: 
```JavaScript
a.always(function(){
  a.cookie("tvn_location2", "1");
});
a.readOnly("TvnAdBlockBoardUtils", function(){});
```

I can see the player, but it gets stuck at loading.

**Comment by X01X012013** [comment]
Widevine doesn't really prevent criminals from pirating videos (like they can just screen record that), what it does is locking people to selected platforms. 
It'll be hard for Google to just say Widevine protected videos, from tomorrow, will only work in Chrome, since video sites won't be happy about it. But what they can do is to secretly make Widevine work just a little bit better on certain platforms. Because laws about DRM, people can't try to figure out why one platform just feels slightly smoother. 
Another reason that Widevine is bad is security professionals are not allowed to look for vulnerabilities in it, and criminals who already committed crimes can abuse these vulnerability to hack into people's devices. You always see news about vulnerabilities in Flash, I bet Widevine is the same, just those vulnerabilities are not disclosed and not fixed. 

That being said, for now, we don't have an effective way to convince developers to unprotect their videos, all we can do is to configure our AdBlockers in a way that isn't detectable by the web page.

**Comment by uBlock-user** [comment]
You can't disable it but you can delete the folder containing the Widewine libs itself and it won't get loaded anymore

**Comment by xxcriticxx** [comment]
this script download from player plus few other pl websites. dont know if we have need for it just for information only 

https://greasyfork.org/pl/scripts/6049-skrypt-umo%C5%BCliwiaj%C4%85cy-pobieranie-materia%C5%82%C3%B3w-ze-znanych-serwis%C3%B3w-vod-autor-przemek/code

**Comment by X01X012013** [comment]
@xxcriticxx I bet it can't download Widevine protected videos. With our native HTML5 player, you will have a download button on the control bar.

**Comment by xxcriticxx** [comment]
This script does multiple website see if don't need any parts of the code

**Comment by X01X012013** [comment]
@xxcriticxx Well, we are not making a video downloader here, it happens to have some downloader functionalities as extra feature.

**Comment by X01X012013** [comment]
I'll close this issue now, since all videos that are not protected are fixed.

**Comment by HateAds** [comment]
@jspenguin2017 https://player.pl/seriale-online/miasto-zla-odcinki,4104/odcinek-2,S00E02,56663.html
![image](https://user-images.githubusercontent.com/29756590/29999314-cb9f7ba2-9043-11e7-9334-d567854f5bed.png)
![image](https://user-images.githubusercontent.com/29756590/29999402-3c05d136-9047-11e7-88b4-0eccd1aa118a.png)

**Comment by jspenguin2017** [comment]
I knew it broke... I'll open another issue for this...

**Comment by jspenguin2017** [comment]
https://github.com/jspenguin2017/uBlockProtector/issues/561
